#!/usr/bin/env bash
set -euo pipefail

command_name="${1:-}"
if [[ "$command_name" != "build" && "$command_name" != "serve" ]]; then
  printf 'usage: %s {build|serve} [zensical args...]\n' "$0" >&2
  exit 2
fi
shift || true

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
docs_root="$script_dir"
site_dir="${DOCBANK_DOCS_SITE_DIR:-site}"

if ! command -v uv >/dev/null 2>&1; then
  printf 'uv not found; install it from https://docs.astral.sh/uv/\n' >&2
  exit 127
fi
uv_run=(uv run --project "$docs_root" --frozen --no-dev)

if [[ -n "${DOCBANK_REPO_ROOT:-}" ]]; then
  repo_root="$(cd "$DOCBANK_REPO_ROOT" && pwd)"
else
  repo_root="$(git -C "$docs_root" rev-parse --show-toplevel)"
fi
if [[ "/$site_dir/" == *"/../"* ]]; then
  printf 'refusing docs site directory containing parent traversal: %s\n' "$site_dir" >&2
  exit 2
fi
site_path="$("${uv_run[@]}" python -c 'import pathlib, sys; print((pathlib.Path(sys.argv[1]) / sys.argv[2]).resolve())' "$docs_root" "$site_dir")"
site_config_dir="$site_dir"
default_site_path="$docs_root/site"
external_site=true
site_source_exclude=""
site_marker=".docbank-docs-output"
site_marker_contents="generated by docbank zensical-docs.sh"
if [[ "$site_path" == "$default_site_path" ]]; then
  external_site=false
fi
if [[ "$site_path" == "$docs_root" || "$site_path" == "$repo_root" || "$docs_root" == "$site_path"/* || "$repo_root" == "$site_path"/* ]]; then
  printf 'refusing unsafe docs site directory: %s\n' "$site_path" >&2
  exit 2
fi
if [[ "$site_path" == "$docs_root/"* ]]; then
  site_source_exclude="./${site_path#"$docs_root/"}"
fi
if [[ "$command_name" == "build" && "$external_site" == true && ( -e "$site_path" || -L "$site_path" ) ]]; then
  if [[ ! -f "$site_path/$site_marker" ]] || [[ "$(<"$site_path/$site_marker")" != "$site_marker_contents" ]]; then
    printf 'refusing to replace non-docbank output directory: %s\n' "$site_path" >&2
    exit 2
  fi
fi

"${uv_run[@]}" python "$docs_root/scripts/check_markdown_sources.py"

tmp_docs=""
tmp_config_base=""
tmp_config=""
tmp_site=""

cleanup() {
  if [[ -n "$tmp_docs" ]]; then
    rm -rf "$tmp_docs"
  fi
  if [[ -n "$tmp_config" ]]; then
    rm -f "$tmp_config"
  fi
  if [[ -n "$tmp_config_base" ]]; then
    rm -f "$tmp_config_base"
  fi
  if [[ -n "$tmp_site" ]]; then
    rm -rf "$tmp_site"
  fi
}
trap cleanup EXIT INT TERM

tmp_site_name="$(cd "$docs_root" && mktemp -d zensical-site.XXXXXX)"
tmp_site="$docs_root/$tmp_site_name"
site_config_dir="$tmp_site_name"

tmp_docs_name="$(cd "$docs_root" && mktemp -d zensical-public-docs.XXXXXX)"
tmp_docs="$docs_root/$tmp_docs_name"
tmp_config_base_name="$(cd "$docs_root" && mktemp .zensical-build.XXXXXX)"
tmp_config_base="$docs_root/$tmp_config_base_name"
tmp_config="$tmp_config_base.toml"
tmp_config_name="$tmp_config_base_name.toml"
if [[ -e "$tmp_config" ]]; then
  printf 'temporary config path already exists: %s\n' "$tmp_config" >&2
  exit 1
fi
mv "$tmp_config_base" "$tmp_config"
tmp_config_base=""

tar_excludes=(
  --exclude './.cache'
  --exclude './.venv'
  --exclude './.env'
  --exclude './.env.*'
  --exclude './internal'
  --exclude './overrides'
  --exclude './scripts'
  --exclude './site'
  --exclude './zensical-site.*'
  --exclude './zensical-public-docs.*'
  --exclude './.zensical-build.*'
  --exclude './superpowers'
  --exclude './README.md'
  --exclude './pyproject.toml'
  --exclude './uv.lock'
  --exclude './zensical-docs.sh'
  --exclude './zensical.toml'
)
if [[ -n "$site_source_exclude" ]]; then
  tar_excludes+=(--exclude "$site_source_exclude")
fi
while IFS= read -r -d '' marker_path; do
  if [[ "$(<"$marker_path")" == "$site_marker_contents" ]]; then
    generated_dir="${marker_path%/*}"
    tar_excludes+=(--exclude "./${generated_dir#"$docs_root/"}")
  fi
done < <(find "$docs_root" -type f -name "$site_marker" -print0)

# The temporary docs tree is the publishing boundary: internal material
# (superpowers specs/plans, tooling, local env) never reaches the site.
(
  cd "$docs_root"
  tar "${tar_excludes[@]}" -cf - .
) | (cd "$tmp_docs" && tar -xf -)

find "$tmp_docs" -depth -name '.*' -exec rm -rf {} +

# tar preserves symlinks, and a symlink could smuggle excluded or
# out-of-tree content (.env, superpowers plans) past the publishing
# boundary when zensical follows it.
symlinks="$(find "$tmp_docs" -type l)"
if [[ -n "$symlinks" ]]; then
  printf 'refusing to publish: symlinks in docs tree:\n%s\n' "$symlinks" >&2
  exit 1
fi

# The installers are published at the site root (docbank.ai/install.sh);
# the repo's scripts/ directory remains their single source of truth.
cp "$repo_root/scripts/install.sh" "$repo_root/scripts/install.ps1" "$tmp_docs/"

awk -v docs_dir="$tmp_docs_name" -v site_dir="$site_config_dir" '
  $0 == "docs_dir = \"docs\"" {
    print "docs_dir = \"" docs_dir "\""
    next
  }
  $0 == "site_dir = \"site\"" {
    print "site_dir = \"" site_dir "\""
    next
  }
  { print }
' "$docs_root/zensical.toml" > "$tmp_config"

case "$command_name" in
  build)
    (cd "$docs_root" && "${uv_run[@]}" zensical build --strict --config-file "$tmp_config_name" "$@")
    while IFS= read -r -d '' markdown_source; do
      markdown_rel="${markdown_source#"$tmp_docs/"}"
      markdown_dest="$tmp_site/$markdown_rel"
      mkdir -p "$(dirname "$markdown_dest")"
      cp "$markdown_source" "$markdown_dest"
    done < <(find "$tmp_docs" -type f -name '*.md' -print0)
    "${uv_run[@]}" python "$docs_root/scripts/check_built_site.py" "$tmp_site" "$tmp_docs" /docs
    printf '%s\n' "$site_marker_contents" > "$tmp_site/$site_marker"
    mkdir -p "$(dirname "$site_path")"
    if [[ -e "$site_path" || -L "$site_path" ]]; then
      if [[ "$external_site" == true ]]; then
        if [[ ! -f "$site_path/$site_marker" ]] || [[ "$(<"$site_path/$site_marker")" != "$site_marker_contents" ]]; then
          printf 'refusing to replace non-docbank output directory: %s\n' "$site_path" >&2
          exit 2
        fi
      fi
      rm -rf -- "$site_path"
    fi
    mv "$tmp_site" "$site_path"
    tmp_site=""
    ;;
  serve)
    (cd "$docs_root" && "${uv_run[@]}" zensical serve --config-file "$tmp_config_name" "$@")
    ;;
esac
